name: Linux Ubuntu Tests

on:
  pull_request:

jobs:
  linux-ubuntu-build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Free up disk space
        run: |
          sudo apt-get clean
          sudo apt-get autoremove -y
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system level dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          sudo apt-get install libopenblas-dev

      - name: Install NVidia compiler
        run: |
          curl https://developer.download.nvidia.com/hpc-sdk/ubuntu/DEB-GPG-KEY-NVIDIA-HPC-SDK | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/nvidia-hpcsdk-archive-keyring.gpg] https://developer.download.nvidia.com/hpc-sdk/ubuntu/amd64 /' | sudo tee /etc/apt/sources.list.d/nvhpc.list
          sudo apt-get update -y
          sudo apt-get install -y nvhpc-25-1

      - name: Install GauOpen and create the mqc-install directory
        run: |
          set -e
          mkdir -p gauopen
          cd gauopen
          echo "Downloading GauOpen..."
          curl --http1.1 -L -f \
            --retry 5 --retry-delay 3 --retry-all-errors \
            -H "User-Agent: Mozilla/5.0" \
            -H "Accept: */*" \
            -o gauopen_v2.zip \
            https://gaussian.com/g16/gauopen_v2.zip
          echo "Verifying zip file..."
          file gauopen_v2.zip
          unzip -t gauopen_v2.zip > /dev/null
          echo "Extracting..."
          unzip gauopen_v2.zip
          cd ..
          mkdir -p mqc-install

      - name: Build mqcPack with gfortran
        run: echo -e "yG$GITHUB_WORKSPACE/mqc-install\n-lblas\n-llapack\n$GITHUB_WORKSPACE/gauopen\ny\nn\n" | ./mqc_install && doxygen doc/Doxyfile

      - name: Build mqcPack with nvfortran
        run: |
          NVARCH=`uname -s`_`uname -m`
          NVCOMPILERS=/opt/nvidia/hpc_sdk
          PATH=$NVCOMPILERS/$NVARCH/25.1/compilers/bin:$PATH; export PATH
          echo -e "yn$GITHUB_WORKSPACE/mqc-install\n-lblas\n-llapack\n$GITHUB_WORKSPACE/gauopen\ny\nn\n" | ./mqc_install && doxygen doc/Doxyfile

